### ISSUE TITLE
Text disappears after edit.

### ISSUE THREAD

**Issue by edherbert** [darksylinc/colibrigui#24]
As of commit 44200cba I'm seeing what seems to be a regression where text disappears in places like editboxes and spinners after any sort of edit. 

From investigation it seems like the fault is with the introduced line

    if( !m_overrideSkinColour )
    	m_colour = m_stateInformation[m_currentState].defaultColour;

In `Colibri::Renderable::setState`.

If this line is commented or removed it works as before. It seems m_stateInformation contains a colour value with all 0s for labels, which causes the text to disappear. `Colibri::Label` does not contain a call to `_setSkinPack` or anything like that, so I think these values aren't being initialized to anything.

I was going to do a pull request because I found a few solutions (you can just set `m_stateInformation.defaultColour` in the label constructor), but I felt like I don't know what the solution is from a code architecture perspective, so I'm raising it as an issue instead.

**Comment by darksylinc** [comment]
Thanks!

There is a raw memset which was overriding the sane default value with all 0s.
