### ISSUE TITLE
Set draw order for windows

### ISSUE THREAD

**Issue by edherbert** [darksylinc/colibrigui#30]
Hello!

I'm writing an FPS counter for my project. I'd like it to sit in the top left, always being drawn on top of anything else. Is there a way to specify the order in which windows are drawn, something like a z-order function?

I imagine it could be done in ColibriManager.cpp::render to just sort the list of windows, but do you know of a better way?

Thanks!

**Comment by darksylinc** [comment]
The order in which windows are created (in other words, the order of `ColibriManager::m_windows` for root windows) is respected.

You can call `window->setVisualsEnabled( false );` which will only hide the window visually _but not its children widgets_. That is one way you can arrange visibility order.

Personally I use this:

```
// C++
m_bgWindow = m_colibriManager->createWindow( 0 );
m_bgWindow->setVisualsEnabled( false );
m_bgWindow->setSkin( "EmptyBg" );
m_bgWindow->setSize( m_colibriManager->getCanvasSize() );
m_bgWindow->m_breadthFirst = true;

// Skins.colibri.json
"EmptyBg" :
{
	"material" : "EmptyBg",
	"tex_resolution" : [1, 1],
	"grid_uv" :
	{
		"all" : [[0, 0, 1, 1], [0, 0]]
	},
	"borders" :
	{
		"all" : [0, 0]
	}
}

// Skins.material
hlms EmptyBg unlit
{
}
```

Currently there is no way to reorder ColibriManager::m_windows (or Window::m_childWindows for windows inside windows), but there is no technical limitation, it could be implemented as a one-time sort whenever the order gets dirty.

I'm trying to stay away from sorting every frame.

**Comment by edherbert** [comment]
Thanks for your quick response dark_sylinc,

Unfortunately your suggestion doesn't really solve my problem. The problem is that some windows are drawn ontop of each other rather than there being problems with transparency. 
![Screenshot from 2020-12-18 12-26-25](https://user-images.githubusercontent.com/4259278/102614882-ec138200-412c-11eb-8d95-ea1b226d794c.png)
You can see this in my very work in progress health bar. Assuming that even with the window background removed the text would still be drawn ontop. For my project I can't control the order in which windows are created, so I need a way to manually specify it.

I'll make an attempt at implementing a system as you suggested with dirty flags to specify changes in order and do a PR. I'll keep speed in mind, I agree we shouldn't be sorting them each frame :)

**Comment by darksylinc** [comment]
You have two ways:

1. A quick hack where you expose m_windows and manually manipulate it
1. Add Window::setZOrder()/getZOrder() which sets an uint16_t and notifies its parent that it is dirty, so that that m_windows / m_childWindows gets queued up for stable re-sorting (based on that u16) on the next update. Sable sort is needed to respect creation order if two windows have the same sort Id.

**Comment by edherbert** [comment]
I've made progress on this.
https://github.com/edherbert/colibrigui/commit/5d3df9e36fc623c9a3fac2b83dc0561e425df2a4
![Peek 2020-12-19 12-46](https://user-images.githubusercontent.com/4259278/102689736-4f1e1b00-41f8-11eb-89ab-50f4e028371e.gif)
Having added a example of it to the demo, it works fine. One problem I had though which makes me consider a re-think. ColibriManager stores a list of windows which are drawn in order, however for windows with child windows the important list is the widgets list. Even though they store a child windows list, they're drawn relative to the widgets list. I ended up having to sort the widgets list trying to avoid anything that wasn't a window.

This makes me think, it would probably be better if all widgets were aware of z-ordering, as then I would be able to sort that list without any of that weirdness. Considering windows inherit from widgets anyway and are attached to parent windows like widgets it makes sense. This means all widgets would have the setZOrder function and store their zOrder (I'm using 8 bits not 16). Does that sound sensible? I'm hoping that won't effect the breadth first traversal or anything (I don't think it will).

**Comment by AllianceDarkSylinc** [comment]
> Even though they store a child windows list, they're drawn relative to the widgets list. I ended up having to sort the widgets list trying to avoid anything that wasn't a window.

I forgot about this.

The solution would be (I'm using 32 bit values but works for 16 and 8):

```
void setZOder( uint32 order )
{
     COLIBRI_ASSERT_LOW( !(order & ( (1u << 31) | (1u << 30) ) ) && "Invalid order value. These bits are reserved" );

     m_order = order;
     // Ensure renderables go after non-renderables
     if( isRenderable() )
         m_order |= 1u<<30u;
     // Ensure windows always go last
     if( isWindow() )
         m_order |= 1u<<31u;
}
```

Btw make sure the relative order of windows in m_children and m_childWindows order matches. While I don't remember that being a problem, it could be in the future. So it's best if they just match.

**Comment by darksylinc** [comment]
> Even though they store a child windows list, they're drawn relative to the widgets list. I ended up having to sort the widgets list trying to avoid anything that wasn't a window.

I forgot about this.

The simple solution would be (I'm using 32 bit values but works for 16 and 8):

```
void setZOder( uint32 order )
{
     COLIBRI_ASSERT_LOW( !(order & ( (1u << 31) | (1u << 30) ) ) && "Invalid order value. These bits are reserved" );

     m_order = order;
     // Ensure renderables go after non-renderables
     if( isRenderable() )
         m_order |= 1u<<30u;
     // Ensure windows always go last
     if( isWindow() )
         m_order |= 1u<<31u;
}
```

Btw make sure the relative order of windows in m_children and m_childWindows order matches. While I don't remember that being a problem, it could be in the future. So it's best if they just match.

**Comment by edherbert** [comment]
I've made it so widgets store the z order and the children and child windows match in their lists.

Quick question, what's the benefit of having the list ordered renderables then windows as described above? I would have thought if the user specified say a window to go behind a button then that's where it should go. Is this just a means to avoid headache later with mouse picking or something?

**Comment by darksylinc** [comment]
Having them sorted that way allows us to perform certain programming tricks such as:

```
itor = m_children.begin();
end = m_children.end();

while( itor != end )
{
// Work on all widgets and windows
++itor;
}

itor = m_children.begin();
end = m_children.begin() + numWindows;

while( itor != end )
{
// Work only on windows
++itor;
}
```

which otherwise requires virtual calls, and keeps the conceptual difference between windows and widgets. And with minimal memory footprint.

Messing up this order will mess up functionality (i.e. it could crash)

As for explicitly rendering a widget below their window, that is unwanted (for non-technical reasons). Colibri follows the [desktop metaphor](https://en.wikipedia.org/wiki/Desktop_metaphor).

And yes, having an object that belongs to a background window being drawn on above a foreground would mess up mouse, keyboard navigation, scrolling and other sort of interactions, not to mention disorienting for users.

There may be an occasional valid case to make an exception where it'd make sense, but more often than not, everyone thinks they've got the best case to make an exception for and the functionality ends up getting abused.

Good UX is really hard. If you mess one little detail your users will notice and suffer.
