### ISSUE TITLE
Its not clear when you need to call sizeToFit

### ISSUE THREAD

**Issue by al2950** [darksylinc/colibrigui#36]
For the tests I have done, it would appear you have to call sizeToFit on every widget to ensure text is displayed correctly. In the demo however this is not always called, but the text always look correct. eg;
https://github.com/darksylinc/colibrigui/blob/fb0545c764f64299a1bf5054d7a0491267a572d7/src/ColibriGuiGameState.cpp#L155-L159

Could you possible add some clarification on when sizeToFit should be called?

**Comment by darksylinc** [comment]
Good point. I'm the one who wrote it thus I usually ignore it.

Where do you think this should be documented? In the sample or in Label's documentation?

**Comment by al2950** [comment]
> In the sample or in Label's documentation?

Can I say both :)

I was also a bit miffed as to what exactly the following achieved in the sample;
https://github.com/darksylinc/colibrigui/blob/fb0545c764f64299a1bf5054d7a0491267a572d7/src/ColibriGuiGameState.cpp#L216-L228

**Comment by darksylinc** [comment]
Hopefully the new comments clarify the problem?

Feel free to reopen if you're left confused.
