### ISSUE TITLE
ColibriGui Pass can render to the wrong rendertarget

### ISSUE THREAD

**Issue by al2950** [darksylinc/colibrigui#37]
https://github.com/darksylinc/colibrigui/blob/fb0545c764f64299a1bf5054d7a0491267a572d7/bin/Data/Main.compositor#L26-L27

Due to the above colibrigui can render to the wrong render target, for example is the pass before is a Clear pass as the clear pass does not set up the RTV. This is not an issue, and I have created my own pass to deal with it, but thought I would raise ticket anyway in case this confused someone else.

**Comment by darksylinc** [comment]
Now that OgreNext 2.3 has `mSkipLoadStoreSemantics` (`skip_load_store_semantics` in scripts) we should be able to easily fix this.

**Comment by darksylinc** [comment]
Fixed.

If you run into this issue, add `skip_load_store_semantics false` to the compositor script.

**Comment by darksylinc** [comment]
Reopening because of a bug (Load & Store actions not handled).

**Comment by darksylinc** [comment]
[Fixed](https://github.com/darksylinc/colibrigui/commit/a085349d1eb0e0bb94050c29098f60706016b42c). This will need upgrading to latest OgreNext 3.0 to fix this issue.
