### ISSUE TITLE
Regression in label rendering causes weirdness

### ISSUE THREAD

**Issue by edherbert** [darksylinc/colibrigui#46]
Hi. I've found that clearing out the text in the editbox in the demo so it shows the placeholder text causes some issues rendering the other labels in the demo.
![Peek 2022-04-24 21-22](https://user-images.githubusercontent.com/4259278/164995357-678b4784-d0cc-4f96-8036-6e63d90e0d38.gif)
When the text box is empty and focused the labels above it flash in and out.

I've traced this back to commit
6526a8e8bb7cbba3d2208c0d2d99b1d7ff7655a2
https://github.com/darksylinc/colibrigui/blob/6526a8e8bb7cbba3d2208c0d2d99b1d7ff7655a2/src/ColibriGui/ColibriRenderable.cpp#L287
Commenting the line out linked above fixes the issue for me. I'd attempt to fix it but don't have any Adreno devices to test this on so I'm raising it as an issue :)

Reproduced on:
arch linux, AMD Radeon RX 5700 XT (navi10, LLVM 13.0.1, DRM 3.44, 5.17.4-arch1-1)
Linux mint 20.3, Mesa Intel(R) UHD Graphics 630
Ogre 2.2.7, 5332186108293c102c09dd2441145c5105ad0994

**Comment by darksylinc** [comment]
The HW bug is that a draw meant to draw 0 vertices would crash the GPU.

This usually happens when a label is empty.

So the fix is "if we don't have anything to draw, don't submit that command". Obviously something went wrong with the fix.

At least I realized why it flashes. It's because the cursor caret keeps flashing.

**Comment by darksylinc** [comment]
I'm researching this problem.

![Screenshot](https://user-images.githubusercontent.com/3395130/165112687-11eb31f9-fbb6-4d5a-9a20-b805f71ca17c.png)

Clearly we're supposed to delete subcommand n° 1 but for some reason we're removing subcommand n° 4

**Comment by darksylinc** [comment]
OK. Now it appears to be fixed for good.
