### ISSUE TITLE
Duplicate code?

### ISSUE THREAD

**Issue by edherbert** [darksylinc/colibrigui#48]
Build currently fails for me as this code is duplicate
https://github.com/darksylinc/colibrigui/blob/783119af6c5aaac5c28de27b9c9b375b57b8840e/src/ColibriGui/ColibriLabelBmp.cpp#L71
I'm guessing this is a mistake.

```
/home/edward/build3/colibri/src/ColibriGui/ColibriLabelBmp.cpp:75:45: error: redeclaration of ‘const String* datablockName’
   75 |                         const Ogre::String *datablockName = datablock->getNameStr();
```

**Comment by darksylinc** [comment]
Thanks. It seems I made a mistake when I transplanted the fix from another project which uses Colibri.
